/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnkeyRouteImport } from './routes/unkey'
import { Route as SerpapiRouteImport } from './routes/serpapi'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GridRouteImport } from './routes/grid'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as FOrgSlugFormSlugRouteImport } from './routes/f/$orgSlug/$formSlug'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as AuthenticatedAppFormsIndexRouteImport } from './routes/_authenticated/app/forms/index'
import { Route as AuthenticatedAppFormsNewRouteImport } from './routes/_authenticated/app/forms/new'
import { Route as AuthenticatedAppFormsFormIdSubmissionsRouteImport } from './routes/_authenticated/app/forms/$formId/submissions'
import { Route as AuthenticatedAppFormsFormIdEditRouteImport } from './routes/_authenticated/app/forms/$formId/edit'

const UnkeyRoute = UnkeyRouteImport.update({
  id: '/unkey',
  path: '/unkey',
  getParentRoute: () => rootRouteImport,
} as any)
const SerpapiRoute = SerpapiRouteImport.update({
  id: '/serpapi',
  path: '/serpapi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const FOrgSlugFormSlugRoute = FOrgSlugFormSlugRouteImport.update({
  id: '/f/$orgSlug/$formSlug',
  path: '/f/$orgSlug/$formSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppFormsIndexRoute =
  AuthenticatedAppFormsIndexRouteImport.update({
    id: '/forms/',
    path: '/forms/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFormsNewRoute =
  AuthenticatedAppFormsNewRouteImport.update({
    id: '/forms/new',
    path: '/forms/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFormsFormIdSubmissionsRoute =
  AuthenticatedAppFormsFormIdSubmissionsRouteImport.update({
    id: '/forms/$formId/submissions',
    path: '/forms/$formId/submissions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFormsFormIdEditRoute =
  AuthenticatedAppFormsFormIdEditRouteImport.update({
    id: '/forms/$formId/edit',
    path: '/forms/$formId/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/grid': typeof GridRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/serpapi': typeof SerpapiRoute
  '/unkey': typeof UnkeyRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/f/$orgSlug/$formSlug': typeof FOrgSlugFormSlugRoute
  '/app/forms/new': typeof AuthenticatedAppFormsNewRoute
  '/app/forms/': typeof AuthenticatedAppFormsIndexRoute
  '/app/forms/$formId/edit': typeof AuthenticatedAppFormsFormIdEditRoute
  '/app/forms/$formId/submissions': typeof AuthenticatedAppFormsFormIdSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/grid': typeof GridRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/serpapi': typeof SerpapiRoute
  '/unkey': typeof UnkeyRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/f/$orgSlug/$formSlug': typeof FOrgSlugFormSlugRoute
  '/app/forms/new': typeof AuthenticatedAppFormsNewRoute
  '/app/forms': typeof AuthenticatedAppFormsIndexRoute
  '/app/forms/$formId/edit': typeof AuthenticatedAppFormsFormIdEditRoute
  '/app/forms/$formId/submissions': typeof AuthenticatedAppFormsFormIdSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/grid': typeof GridRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/serpapi': typeof SerpapiRoute
  '/unkey': typeof UnkeyRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/f/$orgSlug/$formSlug': typeof FOrgSlugFormSlugRoute
  '/_authenticated/app/forms/new': typeof AuthenticatedAppFormsNewRoute
  '/_authenticated/app/forms/': typeof AuthenticatedAppFormsIndexRoute
  '/_authenticated/app/forms/$formId/edit': typeof AuthenticatedAppFormsFormIdEditRoute
  '/_authenticated/app/forms/$formId/submissions': typeof AuthenticatedAppFormsFormIdSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/grid'
    | '/login'
    | '/register'
    | '/serpapi'
    | '/unkey'
    | '/app'
    | '/demo/sentry/testing'
    | '/f/$orgSlug/$formSlug'
    | '/app/forms/new'
    | '/app/forms/'
    | '/app/forms/$formId/edit'
    | '/app/forms/$formId/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/grid'
    | '/login'
    | '/register'
    | '/serpapi'
    | '/unkey'
    | '/app'
    | '/demo/sentry/testing'
    | '/f/$orgSlug/$formSlug'
    | '/app/forms/new'
    | '/app/forms'
    | '/app/forms/$formId/edit'
    | '/app/forms/$formId/submissions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/grid'
    | '/login'
    | '/register'
    | '/serpapi'
    | '/unkey'
    | '/_authenticated/app'
    | '/demo/sentry/testing'
    | '/f/$orgSlug/$formSlug'
    | '/_authenticated/app/forms/new'
    | '/_authenticated/app/forms/'
    | '/_authenticated/app/forms/$formId/edit'
    | '/_authenticated/app/forms/$formId/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  GridRoute: typeof GridRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SerpapiRoute: typeof SerpapiRoute
  UnkeyRoute: typeof UnkeyRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
  FOrgSlugFormSlugRoute: typeof FOrgSlugFormSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unkey': {
      id: '/unkey'
      path: '/unkey'
      fullPath: '/unkey'
      preLoaderRoute: typeof UnkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serpapi': {
      id: '/serpapi'
      path: '/serpapi'
      fullPath: '/serpapi'
      preLoaderRoute: typeof SerpapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/f/$orgSlug/$formSlug': {
      id: '/f/$orgSlug/$formSlug'
      path: '/f/$orgSlug/$formSlug'
      fullPath: '/f/$orgSlug/$formSlug'
      preLoaderRoute: typeof FOrgSlugFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/forms/': {
      id: '/_authenticated/app/forms/'
      path: '/forms'
      fullPath: '/app/forms/'
      preLoaderRoute: typeof AuthenticatedAppFormsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/forms/new': {
      id: '/_authenticated/app/forms/new'
      path: '/forms/new'
      fullPath: '/app/forms/new'
      preLoaderRoute: typeof AuthenticatedAppFormsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/forms/$formId/submissions': {
      id: '/_authenticated/app/forms/$formId/submissions'
      path: '/forms/$formId/submissions'
      fullPath: '/app/forms/$formId/submissions'
      preLoaderRoute: typeof AuthenticatedAppFormsFormIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/forms/$formId/edit': {
      id: '/_authenticated/app/forms/$formId/edit'
      path: '/forms/$formId/edit'
      fullPath: '/app/forms/$formId/edit'
      preLoaderRoute: typeof AuthenticatedAppFormsFormIdEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppFormsNewRoute: typeof AuthenticatedAppFormsNewRoute
  AuthenticatedAppFormsIndexRoute: typeof AuthenticatedAppFormsIndexRoute
  AuthenticatedAppFormsFormIdEditRoute: typeof AuthenticatedAppFormsFormIdEditRoute
  AuthenticatedAppFormsFormIdSubmissionsRoute: typeof AuthenticatedAppFormsFormIdSubmissionsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppFormsNewRoute: AuthenticatedAppFormsNewRoute,
  AuthenticatedAppFormsIndexRoute: AuthenticatedAppFormsIndexRoute,
  AuthenticatedAppFormsFormIdEditRoute: AuthenticatedAppFormsFormIdEditRoute,
  AuthenticatedAppFormsFormIdSubmissionsRoute:
    AuthenticatedAppFormsFormIdSubmissionsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  GridRoute: GridRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SerpapiRoute: SerpapiRoute,
  UnkeyRoute: UnkeyRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
  FOrgSlugFormSlugRoute: FOrgSlugFormSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
