/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnkeyRouteImport } from './routes/unkey'
import { Route as SerpapiRouteImport } from './routes/serpapi'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as GridRouteImport } from './routes/grid'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoWorkosRouteImport } from './routes/demo/workos'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'

const UnkeyRoute = UnkeyRouteImport.update({
  id: '/unkey',
  path: '/unkey',
  getParentRoute: () => rootRouteImport,
} as any)
const SerpapiRoute = SerpapiRouteImport.update({
  id: '/serpapi',
  path: '/serpapi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkosRoute = DemoWorkosRouteImport.update({
  id: '/demo/workos',
  path: '/demo/workos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/grid': typeof GridRoute
  '/register': typeof RegisterRoute
  '/serpapi': typeof SerpapiRoute
  '/unkey': typeof UnkeyRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/grid': typeof GridRoute
  '/register': typeof RegisterRoute
  '/serpapi': typeof SerpapiRoute
  '/unkey': typeof UnkeyRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/grid': typeof GridRoute
  '/register': typeof RegisterRoute
  '/serpapi': typeof SerpapiRoute
  '/unkey': typeof UnkeyRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/grid'
    | '/register'
    | '/serpapi'
    | '/unkey'
    | '/demo/neon'
    | '/demo/prisma'
    | '/demo/workos'
    | '/demo/sentry/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/grid'
    | '/register'
    | '/serpapi'
    | '/unkey'
    | '/demo/neon'
    | '/demo/prisma'
    | '/demo/workos'
    | '/demo/sentry/testing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/grid'
    | '/register'
    | '/serpapi'
    | '/unkey'
    | '/demo/neon'
    | '/demo/prisma'
    | '/demo/workos'
    | '/demo/sentry/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GridRoute: typeof GridRoute
  RegisterRoute: typeof RegisterRoute
  SerpapiRoute: typeof SerpapiRoute
  UnkeyRoute: typeof UnkeyRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoWorkosRoute: typeof DemoWorkosRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unkey': {
      id: '/unkey'
      path: '/unkey'
      fullPath: '/unkey'
      preLoaderRoute: typeof UnkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serpapi': {
      id: '/serpapi'
      path: '/serpapi'
      fullPath: '/serpapi'
      preLoaderRoute: typeof SerpapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workos': {
      id: '/demo/workos'
      path: '/demo/workos'
      fullPath: '/demo/workos'
      preLoaderRoute: typeof DemoWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GridRoute: GridRoute,
  RegisterRoute: RegisterRoute,
  SerpapiRoute: SerpapiRoute,
  UnkeyRoute: UnkeyRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoWorkosRoute: DemoWorkosRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
