/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnkeyRouteImport } from './routes/unkey'
import { Route as SerpapiRouteImport } from './routes/serpapi'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GridRouteImport } from './routes/grid'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'

const UnkeyRoute = UnkeyRouteImport.update({
  id: '/unkey',
  path: '/unkey',
  getParentRoute: () => rootRouteImport,
} as any)
const SerpapiRoute = SerpapiRouteImport.update({
  id: '/serpapi',
  path: '/serpapi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/grid': typeof GridRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/serpapi': typeof SerpapiRoute
  '/unkey': typeof UnkeyRoute
  '/app': typeof AuthenticatedAppRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/grid': typeof GridRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/serpapi': typeof SerpapiRoute
  '/unkey': typeof UnkeyRoute
  '/app': typeof AuthenticatedAppRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/grid': typeof GridRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/serpapi': typeof SerpapiRoute
  '/unkey': typeof UnkeyRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/grid'
    | '/login'
    | '/register'
    | '/serpapi'
    | '/unkey'
    | '/app'
    | '/demo/neon'
    | '/demo/prisma'
    | '/demo/sentry/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/grid'
    | '/login'
    | '/register'
    | '/serpapi'
    | '/unkey'
    | '/app'
    | '/demo/neon'
    | '/demo/prisma'
    | '/demo/sentry/testing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/grid'
    | '/login'
    | '/register'
    | '/serpapi'
    | '/unkey'
    | '/_authenticated/app'
    | '/demo/neon'
    | '/demo/prisma'
    | '/demo/sentry/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  GridRoute: typeof GridRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SerpapiRoute: typeof SerpapiRoute
  UnkeyRoute: typeof UnkeyRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unkey': {
      id: '/unkey'
      path: '/unkey'
      fullPath: '/unkey'
      preLoaderRoute: typeof UnkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serpapi': {
      id: '/serpapi'
      path: '/serpapi'
      fullPath: '/serpapi'
      preLoaderRoute: typeof SerpapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  GridRoute: GridRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SerpapiRoute: SerpapiRoute,
  UnkeyRoute: UnkeyRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
